---
title: 'Desafío 3: Graficar los datos'
output: 
  html_document:
    theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Ahora que ya leiste y te familiarizaste con los datos que elegiste para trabajar, el objetivo de este desafío es generar gráficos que te permitan profundizar en el anaálisis. 

### 1. Abrí tu proyecto

Abrí tu proyecto desde el explorador de archivos (haciendo doble click en el archivo .Rproj) o desde a interfaz de RStudio. Trabajá sobre el mismo Rmd, que ya va tomando forma. Corré el código para cargar esa base de datos en memoria y no te olvides de los paquetes necesarios!

### 2. Generá un gráfico 

Generá un gráfico que muestre la relación entre 2 variables. Podés usar líneas, puntos, mapear el color a una variable distinta o aplicar cualquier cosa que hayamos visto en [Graficos I](06-graficos-I.html) o [Graficos II](07-graficos-II.html) para representar tus datos y ayudarte en el análisis. 

### 3. Resumen de datos

Ahora probá hacer un gráfico usando facetas. 


Podés graficar los datos tanto como se te ocurra, la idea es que te familiarices con ggplot al mismo tiempo que profundizas en el análisis de datos que estás utilizando. Siempre es una buena idea desribir tu interpretación de los gráficos junto al *chunk* correspondiente. 
